<a href="https://colab.research.google.com/github/ekaratnida/DADS5001-Data-Analytics-and-Data-Science-Tools-and-Programming/blob/main/Plotly_go.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Plotly 2 (Express)

In [40]:
import plotly.express as px

df = px.data.gapminder()
print(df.head())
print(df.shape)
print(df['country'].unique())
print(df['gdpPercap'].max())

       country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  
(1704, 8)
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Australia'
 'Austria' 'Bahrain' 'Bangladesh' 'Belgium' 'Benin' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo, Dem. Rep.'
 'Congo, Rep.' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba'
 'Czech Republic' 'Denmark' 'Djibouti' 'Dominican Republic' 'Ecua

In [41]:
max_gdppercap_country = df.loc[df['gdpPercap'].idxmax()]
print(f"The country with the maximum GDP per capita is: {max_gdppercap_country}")

The country with the maximum GDP per capita is: country           Kuwait
continent           Asia
year                1957
lifeExp           58.033
pop               212846
gdpPercap    113523.1329
iso_alpha            KWT
iso_num              414
Name: 853, dtype: object


In [42]:
df = px.data.gapminder().query("country=='Thailand'")
fig = px.line(df, x="year", y="lifeExp", title='Life expectancy in Thailand')
fig.show()

In [53]:
import plotly.express as px

df = px.data.gapminder()
df = df.query("continent=='Europe'")
print(df.head())
print(df.shape)
fig = px.line(df, x="year", y="gdpPercap",color='country',markers=True,symbol='country')
fig.show()

    country continent  year  lifeExp      pop    gdpPercap iso_alpha  iso_num
12  Albania    Europe  1952    55.23  1282697  1601.056136       ALB        8
13  Albania    Europe  1957    59.28  1476505  1942.284244       ALB        8
14  Albania    Europe  1962    64.82  1728137  2312.888958       ALB        8
15  Albania    Europe  1967    66.22  1984060  2760.196931       ALB        8
16  Albania    Europe  1972    67.69  2263554  3313.422188       ALB        8
(360, 8)


In [54]:
import plotly.express as px
df = px.data.stocks()
print(df.head())
print(df.shape)

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708
(105, 7)


In [56]:
#fig = px.line(df, x='date', y="AAPL", markers=True)
fig = px.line(df, x='date', y=["GOOG","AAPL","FB"], markers=True)
fig.show()

In [58]:
import plotly.express as px

df = px.data.stocks()
# Melt the DataFrame to long format
df_melted = df.melt(id_vars='date', value_vars=["GOOG","AAPL","FB"], var_name='company', value_name='price')
df_melted

,date,company,price
0,2018-01-01,GOOG,1.000000
1,2018-01-08,GOOG,1.018172
2,2018-01-15,GOOG,1.032008
3,2018-01-22,GOOG,1.066783
4,2018-01-29,GOOG,1.008773
...,...,...,...
310,2019-12-02,FB,1.075997
311,2019-12-09,FB,1.038855
312,2019-12-16,FB,1.104094
313,2019-12-23,FB,1.113728


In [59]:
fig = px.line(df_melted, x='date', y='price', color='company', markers=True, symbol='company')
fig.show()

In [60]:
import plotly.express as px
df = px.data.stocks(indexed=True)
df.head()

company,GOOG,AAPL,AMZN,FB,NFLX,MSFT
date,,,,,,
2018-01-01,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2018-01-08,1.018172,1.011943,1.061881,0.959968,1.053526,1.015988
2018-01-15,1.032008,1.019771,1.053240,0.970243,1.049860,1.020524
2018-01-22,1.066783,0.980057,1.140676,1.016858,1.307681,1.066561
2018-01-29,1.008773,0.917143,1.163374,1.018357,1.273537,1.040708


In [71]:
fig = px.line(df, facet_row="company", facet_row_spacing=0.01, height=400, width=800)
fig.show()

In [72]:
#hide and lock down axes
fig.update_xaxes(visible=False, fixedrange=True)
fig.update_yaxes(visible=False, fixedrange=True)
fig.show()

In [73]:
# remove facet/subplot labels
fig.update_layout(annotations=[], overwrite=True)
fig.show()

In [86]:
# strip down the rest of the plot
fig.update_layout(
    showlegend=True,
    plot_bgcolor="yellow",
    paper_bgcolor="black",
    margin=dict(t=20,l=10,b=20,r=10)
)

fig.update_legends(bgcolor="yellow")

# disable the modebar for such a small plot
fig.show(config=dict(displayModeBar=False))

## Exercise1. Convert the line chart above to bar chart.

## Plotly 2 (Go Objects)

In [49]:
import plotly.graph_objects as go
df = px.data.stocks()

# Create traces
fig = go.Figure()
fig.add_trace(go.Scatter(x=df.date, y=df.GOOG,
                    mode='lines',
                    name='Google'))
fig.add_trace(go.Scatter(x=df.date, y=df.AAPL,
                    mode='lines+markers',
                    name='Apple'))
fig.add_trace(go.Scatter(x=df.date, y=df.AMZN,
                    mode='markers', name='Amazon'))

fig.show()

## AI generated

In [50]:
import plotly.graph_objects as go
import plotly.express as px

df = px.data.stocks()

fig = go.Figure()
fig.add_trace(go.Scattergl(
    x=df.date, y=df['GOOG'],
    mode='lines',
    line_color='deepskyblue',
    name='GOOG',
    hoverinfo='name+x+y',
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="Rockwell"
    )
))

fig.add_trace(go.Scattergl(
    x=df.date, y=df['AAPL'],
    mode='lines',
    line_color='dimgray',
    name='AAPL',
    hoverinfo='name+x+y',
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="Rockwell"
    )
))

fig.add_trace(go.Scattergl(
    x=df.date, y=df['AMZN'],
    mode='lines',
    line_color='lightcoral',
    name='AMZN',
    hoverinfo='name+x+y',
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="Rockwell"
    )
))

fig.update_layout(
    title="Hover on traces",
    hovermode="x unified",
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=True,
    plot_bgcolor='white'
)

fig.show()

In [51]:
import plotly.graph_objects as go
import plotly.express as px

df = px.data.stocks()

# Calculate percentage difference from the first value for each stock
df_pct = df.copy()
for col in df.columns[1:4]:
    df_pct[col] = (df[col] / df[col].iloc[0] - 1) * 100

fig = go.Figure()

for col in df_pct.columns[1:4]:
    fig.add_trace(go.Scattergl(
        x=df_pct.date, y=df_pct[col],
        mode='lines',
        name=col,
        hoverinfo='name+x+y'
    ))

fig.update_layout(
    title="Percentage Difference of Stocks from Start Date",
    hovermode="x unified",
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    yaxis=dict(
        title="Percentage Difference (%)",
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=True,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=True,
    plot_bgcolor='white'
)

fig.show()

In [52]:
import plotly.graph_objects as go
import numpy as np

title = 'Main Source for News'
labels = ['Television', 'Newspaper', 'Internet', 'Radio']
colors = ['rgb(67,67,67)', 'rgb(115,115,115)', 'rgb(49,130,189)', 'rgb(189,189,189)']

mode_size = [8, 8, 12, 8]
line_size = [2, 2, 4, 2]

x_data = np.vstack((np.arange(2001, 2014),)*4)
print(x_data)

y_data = np.array([
    [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
    [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
    [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
])

fig = go.Figure()

for i in range(0, 4):
    fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], mode='lines',
        name=labels[i],
        line=dict(color=colors[i], width=line_size[i]),
        connectgaps=True,
    ))

    # endpoints
    fig.add_trace(go.Scatter(
        x=[x_data[i][0], x_data[i][-1]],
        y=[y_data[i][0], y_data[i][-1]],
        mode='markers',
        marker=dict(color=colors[i], size=mode_size[i])
    ))
    print([x_data[i][0], x_data[i][-1]])

fig.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=False,
    plot_bgcolor='white'
)

annotations = []

# Adding labels
for y_trace, label, color in zip(y_data, labels, colors):
    # labeling the left_side of the plot
    annotations.append(dict(xref='paper', x=0.05, y=y_trace[0],
                                  xanchor='right', yanchor='middle',
                                  text=label + ' {}%'.format(y_trace[0]),
                                  font=dict(family='Arial',
                                            size=16),
                                  showarrow=False))
    # labeling the right_side of the plot
    annotations.append(dict(xref='paper', x=0.95, y=y_trace[11],
                                  xanchor='left', yanchor='middle',
                                  text='{}%'.format(y_trace[11]),
                                  font=dict(family='Arial',
                                            size=16),
                                  showarrow=False))
# Title
annotations.append(dict(xref='paper', yref='paper', x=0.0, y=1.05,
                              xanchor='left', yanchor='bottom',
                              text='Main Source for News',
                              font=dict(family='Arial',
                                        size=30,
                                        color='rgb(37,37,37)'),
                              showarrow=False))
# Source
annotations.append(dict(xref='paper', yref='paper', x=0.5, y=-0.1,
                              xanchor='center', yanchor='top',
                              text='Source: PewResearch Center & ' +
                                   'Storytelling with data',
                              font=dict(family='Arial',
                                        size=12,
                                        color='rgb(150,150,150)'),
                              showarrow=False))

fig.update_layout(annotations=annotations)

fig.show()

[[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
